### ISSUE TITLE
Building with Vite... Failed

### ISSUE THREAD

**Issue by thomas992** [bmatthieu3/wgpu-sky-rendering#2]
```
[nix-shell:~/Games/wgpu-sky-rendering]$ npm run build && vite

> allsky_proj@1.0.0 build
> npm run wasm && vite build


> allsky_proj@1.0.0 wasm
> wasm-pack build --target web --release

[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
warning: unused import: `cgmath::InnerSpace`
  --> src/lib.rs:83:5
   |
83 | use cgmath::InnerSpace;
   |     ^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `allsky-proj` (lib) generated 1 warning (run `cargo fix --lib -p allsky-proj` to apply 1 suggestion)
    Finished `release` profile [optimized] target(s) in 0.07s
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: ✨   Done in 43.41s
[INFO]: 📦   Your wasm pkg is ready to publish at /home/tommhnsn/Games/wgpu-sky-rendering/pkg.
[WARN]: ⚠️   There's a newer version of wasm-pack available, the new version is: 0.13.0, you are using: 0.12.1. To update, navigate to: https://rustwasm.github.io/wasm-pack/installer/
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.4.2 building for production...
✓ 0 modules transformed.
x Build failed in 66ms
error during build:
[vite-plugin-wasm-pack] ENOENT: no such file or directory, open '/home/tommhnsn/Games/wgpu-sky-rendering/pkg/wgpu_sky_rendering_bg.wasm'
    at Object.openSync (node:fs:573:18)
    at Object.readFileSync (node:fs:452:35)
    at /home/tommhnsn/Games/wgpu-sky-rendering/node_modules/.pnpm/vite-plugin-wasm-pack@0.1.12/node_modules/vite-plugin-wasm-pack/dist/index.js:163:48
    at Map.forEach (<anonymous>)
    at Object.buildEnd (/home/tommhnsn/Games/wgpu-sky-rendering/node_modules/.pnpm/vite-plugin-wasm-pack@0.1.12/node_modules/vite-plugin-wasm-pack/dist/index.js:159:21)
    at file:///home/tommhnsn/Games/wgpu-sky-rendering/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:19913:40
    at async Promise.all (index 1)
    at async PluginDriver.hookParallel (file:///home/tommhnsn/Games/wgpu-sky-rendering/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:19841:9)
    at async file:///home/tommhnsn/Games/wgpu-sky-rendering/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20758:13
    at async catchUnfinishedHookActions (file:///home/tommhnsn/Games/wgpu-sky-rendering/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20258:16)

```

this is my shell.nix

```
 {
   pkgs ? import <nixpkgs> { }, # here we import the nixpkgs packages
 }:
 # mkShell is a helper function
 pkgs.mkShell {
   name = "dev-environment"; # that requires a name
   buildInputs = [
     # and a list of packages
     pkgs.rustc
     pkgs.cargo
     pkgs.wasm-pack
     pkgs.lld
     pkgs.nodejs
     pkgs.nodePackages.pnpm
   ];
   shellHook = ''
     # bash to run when you enter the shell
     echo "Start developing..."
   '';
 }
```
I had to use pnpm to do "npm install" and install Vite for some reason.

I have tried using the other command for building that was in the readme and it resulted in error.

```
[nix-shell:~/Games/wgpu-sky-rendering]$ cargo run --release
warning: unused import: `cgmath::InnerSpace`
  --> src/lib.rs:83:5
   |
83 | use cgmath::InnerSpace;
   |     ^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `allsky-proj` (lib) generated 1 warning (run `cargo fix --lib -p allsky-proj` to apply 1 suggestion)
    Finished `release` profile [optimized] target(s) in 0.08s
     Running `target/release/allsky-proj`
thread 'main' panicked at /home/tommhnsn/Games/wgpu-sky-rendering/src/lib.rs:632:39:
called `Result::unwrap()` on an `Err` value: NotSupported(NotSupportedError)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Pop! OS 22.04

**Comment by bmatthieu3** [comment]
The vite setup is not finished.
But the cargo run --release should work.
With a google search I found that issue: https://github.com/rust-windowing/winit/issues/3603
It seems pretty correlated with what you have.
